# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
raw_data = pd.read_csv('hotel_bookings.csv')
raw_data.sample(8)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
29499,Resort Hotel,0,17,2016,October,44,27,0,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,E,0,No Deposit,240.0,NaN,0,Transient,122.67,1,2,Check-Out,30-10-16
71818,City Hotel,1,414,2017,July,28,13,0,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,B,1,No Deposit,6.0,NaN,0,Transient-Party,80.00,0,0,Canceled,28-06-17
82322,City Hotel,0,35,2015,December,53,28,1,0,2,2.0,0,SC,PRT,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,9.0,NaN,0,Contract,150.30,0,1,Check-Out,29-12-15
106146,City Hotel,0,3,2017,February,8,21,0,1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,14.0,NaN,0,Transient,107.00,0,0,Check-Out,22-02-17
67011,City Hotel,1,111,2017,April,17,27,1,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,31.0,NaN,0,Transient,120.00,0,0,Canceled,06-01-17
51281,City Hotel,1,64,2016,May,21,17,0,2,2,0.0,0,BB,PRT,Corporate,TA/TO,0,0,0,A,B,1,No Deposit,NaN,218.0,0,Transient-Party,140.00,0,0,Canceled,05-05-16
43748,City Hotel,0,86,2015,September,39,24,0,2,1,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,12.0,NaN,0,Transient-Party,87.50,0,0,Check-Out,26-09-15
113754,City Hotel,0,130,2017,June,23,8,0,3,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,189.00,0,3,Check-Out,11-06-17

## 1. Data Collection

In [3]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

- There are 32 columns in the dataset.
- The dataset contains 119,390 rows.
- Data Types:
    - 1. 16 columns are of int64 data type.
    - 2. 4 columns are of float64 data type.
    - 3. 12 columns are of object data types. 
- Missing Values:
    - The column `children` has <span style="color:red">4</span> missing values.
    - The column `country` has <span style="color:red">488</span> missing values.
    - The column `agent` has <span style="color:red">16,340</span> missing values.
    - The column `company` has <span style="color:red">112,593</span> missing values.

## 2 Exploratory Data Analysis (EDA)

### 2.1 Looking for missing values.

In [4]:
raw_data.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

- Dropping null values is easy but isn't a good practice, so we will start with replacing them with zero.

In [5]:
raw_data.fillna(0, inplace=True)

### 2.2 cleaning Data

In [6]:
raw_data.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119390.0,0.103886,0.398555,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,119390.0,74.828319,107.141953,0.00,7.00,9.000,152.0,535.0
company,119390.0,10.775157,53.943884,0.00,0.00,0.000,0.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [7]:
# Display rows with negative adr values
negative_adr_rows = raw_data[raw_data['adr'] < 0]
display(negative_adr_rows)

# Drop rows with negative adr values
raw_data.drop(negative_adr_rows.index, inplace=True)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
14969,Resort Hotel,0,195,2017,March,10,5,4,6,2,0.0,0,BB,GBR,Groups,Direct,1,0,2,A,H,2,No Deposit,273.0,0.0,0,Transient-Party,-6.38,0,0,Check-Out,15-03-17

### Based on the following logic:

1.  Rows containing negative values in the `adr` column.
2.  The `distribution_channel` column, as it depicts the same information as the `market_segment` column.
3.  The `arrival_date_week_number` column, as the week number can be derived from the `arrival_date` column.
4.  Rows where both the `children` and `adults` columns contain zero.

In [8]:
def clean_dataframe(data):
    """
    Cleans a pandas DataFrame based on specified criteria.

    Args:
        raw_data: The pandas DataFrame to clean.

    Returns:
        The cleaned pandas DataFrame.
    """

    # 1. Drop rows with negative 'adr' values.
    data.drop(data[data['adr'] <= 0].index, inplace=True)

    # 2. Drop the 'distribution_channel' column.
    if 'distribution_channel' in data.columns: # check if column exists
        data = data.drop(columns=['distribution_channel'])

    # 3. Drop the 'arrival_date_week_number' column.
    if 'arrival_date_week_number' in data.columns: # check if column exists
        data = data.drop(columns=['arrival_date_week_number'])

    # 4. Drop rows where both 'children' and 'adults' are zero.
    data = data[~((data['children'] == 0) & (data['adults'] == 0))] # ~ is the not operator.

    return data


raw_data = clean_dataframe(raw_data)

In [9]:
raw_data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
2,Resort Hotel,0,7,2015,July,1,0,1,1,0.0,0,BB,GBR,Direct,0,0,0,A,C,0,No Deposit,0.0,0.0,0,Transient,75.00,0,0,Check-Out,02-07-15
3,Resort Hotel,0,13,2015,July,1,0,1,1,0.0,0,BB,GBR,Corporate,0,0,0,A,A,0,No Deposit,304.0,0.0,0,Transient,75.00,0,0,Check-Out,02-07-15
4,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,0,BB,GBR,Online TA,0,0,0,A,A,0,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,03-07-15
5,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,0,BB,GBR,Online TA,0,0,0,A,A,0,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,03-07-15
6,Resort Hotel,0,0,2015,July,1,0,2,2,0.0,0,BB,PRT,Direct,0,0,0,C,C,0,No Deposit,0.0,0.0,0,Transient,107.00,0,0,Check-Out,03-07-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,0,0,0,A,A,0,No Deposit,394.0,0.0,0,Transient,96.14,0,0,Check-Out,06-09-17
119386,City Hotel,0,102,2017,August,31,2,5,3,0.0,0,BB,FRA,Online TA,0,0,0,E,E,0,No Deposit,9.0,0.0,0,Transient,225.43,0,2,Check-Out,07-09-17
119387,City Hotel,0,34,2017,August,31,2,5,2,0.0,0,BB,DEU,Online TA,0,0,0,D,D,0,No Deposit,9.0,0.0,0,Transient,157.71,0,4,Check-Out,07-09-17
119388,City Hotel,0,109,2017,August,31,2,5,2,0.0,0,BB,GBR,Online TA,0,0,0,A,A,0,No Deposit,89.0,0.0,0,Transient,104.40,0,0,Check-Out,07-09-17
119389,City Hotel,0,205,2017,August,29,2,7,2,0.0,0,HB,DEU,Online TA,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,151.20,0,2,Check-Out,07-09-17

### 2.3 Feature Selection

##### Why Feature Selection Might Be Beneficial:

* **Improved LLM Performance:** LLMs can be sensitive to irrelevant or redundant information. Feature selection can help focus the LLM on the most important data points, potentially improving accuracy and relevance.

* **Reduced Dimensionality:** If your dataset has a large number of features, feature selection can reduce the dimensionality of the data. This can lead to:

    1.  Faster vector embedding generation and retrieval.
    2.  Reduced storage requirements for your vector database.
    3.  Improved efficiency of your API.

In [10]:
raw_data['booking_source'] = np.where(
    (raw_data['agent'] > 0) & (raw_data['agent'].notna()), 
    'agent',
    np.where(
        (raw_data['company'] > 0) & (raw_data['company'].notna()),
        'company',
        'self'
    )
)

# Enhanced customer history features (FIXED VERSION)
raw_data['previous_experience'] = np.where(
    raw_data['is_repeated_guest'] == 1,
    'Repeat',
    'First-time'
)

# For previous cancellations analysis
raw_data['previous_cancel_behavior'] = np.where(
    raw_data['previous_cancellations'] > 0,
    'Previous Canceller',
    'No Cancel History'
)

# Create customer segments
conditions = [
    raw_data['previous_cancellations'] > 0,
    raw_data['is_repeated_guest'] == 1,
    raw_data['total_of_special_requests'] > 2
]
choices = ['Risk', 'Loyal', 'High-Maintenance']
raw_data['customer_segment'] = np.select(conditions, choices, default='Standard')

raw_data['arrival_date'] = pd.to_datetime(
    raw_data['arrival_date_year'].astype(str) + '-' +
    raw_data['arrival_date_month'] + '-' +
    raw_data['arrival_date_day_of_month'].astype(str)
)

columns_to_drop = [
    'arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month',
    'assigned_room_type','days_in_waiting_list', 'reservation_status_date',
    'agent', 'company','is_repeated_guest', 'previous_cancellations','reservation_status'
]
raw_data.drop(columns=columns_to_drop, inplace=True)

- Combinied the `agent` and `company` columns into a single `booking_source` column.
- Determines whether a booking was made through an **agent**, a **company**, or directly by the customer (**self**).

- Created a new column `previous_experience` to categorise customers as either **Repeat** or **First-time** guests.
- Created a new column `previous_cancel_behavior` to categorise customers based on their cancellation history.
- Combined `arrival_date_year`, `arrival_date_month`, and `arrival_date_day_of_month` into a single `arrival_date` column.
- Removed redundant or unnecessary columns from the dataset, to focuses on features that are most relevant for analytics and chatbot queries.

In [11]:
raw_data.to_csv('cleaned_hotel_bookings.csv', index=False)

### 2.4 Chatbot-Focused Text Representation

In [12]:
def create_chatbot_entry(row):
    # Format dates
    arrival_date = row['arrival_date'].strftime('%b %d, %Y')
    
    # Convert codes to human-readable formats
    meal_map = {
        'BB': 'Bed & Breakfast',
        'HB': 'Half Board',
        'FB': 'Full Board',
        'SC': 'Self Catering'
    }
    
    customer_type_map = {
        'Transient': 'Individual Traveler',
        'Contract': 'Corporate Contract',
        'Group': 'Tour Group',
        'Transient-Party': 'Travel Group'
    }
    
    return f"""
    {row['hotel']} booking {'CANCELED' if row['is_canceled'] else 'CONFIRMED'}.
    - Dates: Arriving {arrival_date} for {row['stays_in_weekend_nights']+row['stays_in_week_nights']} nights
    - Guests: {row['adults']} adults, {row['children']} children
    - Room: {row['reserved_room_type']} (Booked), {row.get('assigned_room_type', row['reserved_room_type'])} (Assigned)
    - Pricing: ${row['adr']:.2f} per night (Total: ${row['adr']*(row['stays_in_weekend_nights']+row['stays_in_week_nights']):.2f})
    - Special Requests: {row['total_of_special_requests']} ({'No parking needed' if row['required_car_parking_spaces'] == 0 else 'Parking required'})
    - Customer Profile: {customer_type_map.get(row['customer_type'], row['customer_type'])} | {row['previous_experience']} guest
    - Booking Source: {row['booking_source']} via {row['market_segment']}
    - Risk Factors: {row['previous_cancel_behavior']} | {row['customer_segment']} segment
    - Meal Plan: {meal_map.get(row['meal'], row['meal'])}
    - Country: {row['country']}
    """

raw_data['chatbot_text'] = raw_data.apply(create_chatbot_entry, axis=1)